### ISSUE TITLE
Not found, while second step with wget, ERROR 404: Not Found.

### ISSUE THREAD

**Issue by michaelsjackson** [tmbarchive/ocropy#336] opened 2020-05-24 23:36 UTC
```
wget -nd http://www.tmbdev.net/en-default.pyrnn.gz
  http://www.tmbdev.net/en-default.pyrnn.gz
Resolving www.tmbdev.net (www.tmbdev.net)... 64.90.41.183
Connecting to www.tmbdev.net (www.tmbdev.net)|64.90.41.183|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-05-25 01:34:17 ERROR 404: Not Found.

```

**Comment by amitdo** [comment] 2020-05-24 23:48
Duplicate of #333.

**Closed** 2020-05-25 00:03 UTC
